# Generated by Django 3.1 on 2020-09-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200909_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default=12345, max_length=20),
            preserve_default=False,
        ),
    ]
