# Generated by Django 3.1 on 2020-09-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='media',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.URLField(default='https://via.placeholder.com/300x400?text=No+photo', max_length=900),
        ),
    ]
