# Generated by Django 3.1 on 2020-09-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200911_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='media',
        ),
    ]
